export const exchangeRates = [
  {
    country: 'Australia',
    currency: 'dollar',
    amount: 1,
    code: 'AUD',
    rate: 15.126,
    ratePer100CZK: 6.61,
  },
  {
    country: 'Brazil',
    currency: 'real',
    amount: 1,
    code: 'BRL',
    rate: 4.018,
    ratePer100CZK: 24.89,
  },
  {
    country: 'Bulgaria',
    currency: 'lev',
    amount: 1,
    code: 'BGN',
    rate: 12.872,
    ratePer100CZK: 7.77,
  },
  {
    country: 'Canada',
    currency: 'dollar',
    amount: 1,
    code: 'CAD',
    rate: 16.825,
    ratePer100CZK: 5.94,
  },
  {
    country: 'China',
    currency: 'renminbi',
    amount: 1,
    code: 'CNY',
    rate: 3.337,
    ratePer100CZK: 29.97,
  },
  {
    country: 'Denmark',
    currency: 'krone',
    amount: 1,
    code: 'DKK',
    rate: 3.374,
    ratePer100CZK: 29.64,
  },
  {
    country: 'EMU',
    currency: 'euro',
    amount: 1,
    code: 'EUR',
    rate: 25.175,
    ratePer100CZK: 3.97,
  },
  {
    country: 'Hongkong',
    currency: 'dollar',
    amount: 1,
    code: 'HKD',
    rate: 3.121,
    ratePer100CZK: 32.04,
  },
  {
    country: 'Hungary',
    currency: 'forint',
    amount: 100,
    code: 'HUF',
    rate: 6.12,
    ratePer100CZK: 1633.99,
  },
  {
    country: 'Iceland',
    currency: 'krona',
    amount: 100,
    code: 'ISK',
    rate: 17.255,
    ratePer100CZK: 579.54,
  },
  {
    country: 'IMF',
    currency: 'SDR',
    amount: 1,
    code: 'XDR',
    rate: 31.54,
    ratePer100CZK: 3.17,
  },
  {
    country: 'India',
    currency: 'rupee',
    amount: 100,
    code: 'INR',
    rate: 28.063,
    ratePer100CZK: 356.34,
  },
  {
    country: 'Indonesia',
    currency: 'rupiah',
    amount: 1000,
    code: 'IDR',
    rate: 1.488,
    ratePer100CZK: 67204.3,
  },
  {
    country: 'Israel',
    currency: 'new shekel',
    amount: 1,
    code: 'ILS',
    rate: 6.786,
    ratePer100CZK: 14.74,
  },
  {
    country: 'Japan',
    currency: 'yen',
    amount: 100,
    code: 'JPY',
    rate: 15.611,
    ratePer100CZK: 640.57,
  },
  {
    country: 'Malaysia',
    currency: 'ringgit',
    amount: 1,
    code: 'MYR',
    rate: 5.43,
    ratePer100CZK: 18.42,
  },
  {
    country: 'Mexico',
    currency: 'peso',
    amount: 1,
    code: 'MXN',
    rate: 1.171,
    ratePer100CZK: 85.4,
  },
  {
    country: 'New Zealand',
    currency: 'dollar',
    amount: 1,
    code: 'NZD',
    rate: 13.676,
    ratePer100CZK: 7.31,
  },
  {
    country: 'Norway',
    currency: 'krone',
    amount: 1,
    code: 'NOK',
    rate: 2.13,
    ratePer100CZK: 46.95,
  },
  {
    country: 'Philippines',
    currency: 'peso',
    amount: 100,
    code: 'PHP',
    rate: 41.518,
    ratePer100CZK: 240.86,
  },
  {
    country: 'Poland',
    currency: 'zloty',
    amount: 1,
    code: 'PLN',
    rate: 5.92,
    ratePer100CZK: 16.89,
  },
  {
    country: 'Romania',
    currency: 'leu',
    amount: 1,
    code: 'RON',
    rate: 5.058,
    ratePer100CZK: 19.77,
  },
  {
    country: 'Singapore',
    currency: 'dollar',
    amount: 1,
    code: 'SGD',
    rate: 17.881,
    ratePer100CZK: 5.59,
  },
  {
    country: 'South Africa',
    currency: 'rand',
    amount: 1,
    code: 'ZAR',
    rate: 1.306,
    ratePer100CZK: 76.57,
  },
  {
    country: 'South Korea',
    currency: 'won',
    amount: 100,
    code: 'KRW',
    rate: 1.686,
    ratePer100CZK: 5931.2,
  },
  {
    country: 'Sweden',
    currency: 'krona',
    amount: 1,
    code: 'SEK',
    rate: 2.194,
    ratePer100CZK: 45.58,
  },
  {
    country: 'Switzerland',
    currency: 'franc',
    amount: 1,
    code: 'CHF',
    rate: 26.709,
    ratePer100CZK: 3.74,
  },
  {
    country: 'Thailand',
    currency: 'baht',
    amount: 100,
    code: 'THB',
    rate: 71.339,
    ratePer100CZK: 140.18,
  },
  {
    country: 'Turkey',
    currency: 'lira',
    amount: 100,
    code: 'TRY',
    rate: 68.208,
    ratePer100CZK: 146.61,
  },
  {
    country: 'United Kingdom',
    currency: 'pound',
    amount: 1,
    code: 'GBP',
    rate: 29.768,
    ratePer100CZK: 3.36,
  },
  {
    country: 'USA',
    currency: 'dollar',
    amount: 1,
    code: 'USD',
    rate: 24.301,
    ratePer100CZK: 4.12,
  },
]